name: Generate changelog
on:
  release:
    types: [created, edited]
  push:
    branches: [$default-branch]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: joshlynchONS/gov-changelog-action@first_action
      with:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
